In [1]:
import cv2
import numpy as np
import os

In [2]:
images=[]
labels=[]
for i in range(1,4):
    for j in os.listdir(f'F:/ML/dataset/{i}'):
        img=cv2.imread(f'F:/ML/dataset/{i}/'+j,cv2.IMREAD_GRAYSCALE)
        images.append(img)
        labels.append(i)

In [3]:
X=np.array(images)
y=np.array(labels)

In [4]:
X.shape

(18831, 28, 28)

In [5]:
y.shape

(18831,)

In [6]:
X=X.reshape(len(X),-1)

In [7]:
X.shape

(18831, 784)

In [8]:
from sklearn.decomposition import PCA

In [9]:
pca=PCA(.99)

In [10]:
new_X=pca.fit_transform(X)

In [11]:
new_X.shape

(18831, 300)

In [12]:
from sklearn.linear_model import LogisticRegression



In [13]:
lr=LogisticRegression()

In [14]:
lr.fit(new_X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [33]:
test_img=cv2.imread('F:/ML/dataset/1.png')
test_gray=cv2.cvtColor(test_img,cv2.COLOR_BGR2GRAY)
test_gray=test_gray.reshape(1,-1)
test_X=pca.transform(test_gray)
lr.predict(test_X)

array([1])

In [34]:
test_img=cv2.imread('F:/ML/dataset/2.png')
test_gray=cv2.cvtColor(test_img,cv2.COLOR_BGR2GRAY)
test_gray=test_gray.reshape(1,-1)
test_X=pca.transform(test_gray)
lr.predict(test_X)

array([2])

In [35]:
test_img=cv2.imread('F:/ML/dataset/3.png')
test_gray=cv2.cvtColor(test_img,cv2.COLOR_BGR2GRAY)
test_gray=test_gray.reshape(1,-1)
test_X=pca.transform(test_gray)
lr.predict(test_X)

array([3])

In [36]:
test_gray.shape

(1, 784)

In [20]:
test_gray.shape

(1, 144316)